#!/usr/bin/env bash
export EDITOR=${EDITOR:=notepad}
WIN_BASE=`dirname $0`
UNIX_BASE=`cygpath "$WIN_BASE"`
export PATH="$PATH:$UNIX_BASE/bootstrap-3_8_0_chromium_8_bin/python/bin:$UNIX_BASE/bootstrap-3_8_0_chromium_8_bin/python/bin/Scripts:$UNIX_BASE/bootstrap-3_8_0_chromium_8_bin/python3/bin:$UNIX_BASE/bootstrap-3_8_0_chromium_8_bin/python3/bin/Scripts"
export PYTHON_DIRECT=1
export PYTHONUNBUFFERED=1
if [[ $# > 0 ]]; then
  $UNIX_BASE/bootstrap-3_8_0_chromium_8_bin/git/bin/bash.exe "$@"
else
  $UNIX_BASE/bootstrap-3_8_0_chromium_8_bin/git/git-bash.exe &
fi
